###
//Crear un elemento en la base de datos
POST https://catalogoflutter.onrender.com/api/catalogo HTTP/1.1
Content-Type: application/json

{
    "nombre": "Camisa johana",
    "precio": 50000,
    "imagen": "camisa johana"
}

###
//Mostrar todos los datos
GET https://catalogoflutter.onrender.com/api/catalogo HTTP/1.1

###
//Listar un elemento o dato con el id
GET https://catalogoflutter.onrender.com/api/catalogo/66121f82beab98eb9c0153bb HTTP/1.1

###
//Actualizar un elemto de la base de datos
PUT https://catalogoflutter.onrender.com/api/catalogo/66121f82beab98eb9c0153bb HTTP/1.1
Content-Type: application/json

{
    "nombre": "Camisa Batman",
    "precio": 50000,
    "imagen": "camisa Batman"
}

###
//Borrar un elemento de la base de datos
DELETE https://catalogoflutter.onrender.com/api/catalogo/66121f82beab98eb9c0153bb HTTP/1.1
